/* generated by dia/codegen.py */
/*(NULL)*/
class Macierz 
{
};

/*(NULL)*/
class GoraZOstrymSzczytem 
{
};

/*(NULL)*/
class Scena 
{
};

/*(NULL)*/
class Bryla_Geometryczna 
{
};

/*(NULL)*/
class Prostopadloscian 
{
};

/*(NULL)*/
class Plaskowyz 
{
};

/*(NULL)*/
class Wektor3D 
{
};

/*(NULL)*/
class MacierzObrotu 
{
};

/*(NULL)*/
class Graniastoslup6 
{
};



/*(NULL)*/
class Wektor 
{
};

/*(NULL)*/
class GoraZGrania 
{
};

/*(NULL)*/
class Macierz3x3 
{
};

/*(NULL)*/
class Podloze 
{
};

/*Klasa modelująca drona. Umożliwia zadawanie dronu przelotów do wykonania.*/
class Dron 
{
public:
	/* Metoda zadaje dronu przelot do wykonania. Zwraca true jeśli parametry zadanego przelotu są prawidłowe i zadaje przelot. Zwraca false jeśli parametry przelotu są nieprawidłowe i nie zadaje przelotu. */
	bool zadajPrzelot ();
	/* Metoda wykonuje pojedynczy krok drona. Złożenie wielu takich kroków ma skutkować animacją przelotu drona. Metoda zwraca true jeśli wykonano krok. Metoda zwraca false jeśli nie pozostało więcej kroków do wykonania. */
	bool wykonajKrok ();
};

